# Имя workflow и когда его запускать
name: Build Windows EXE

# Триггер: при каждом пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  build-windows:
    # Используем готовую Windows-среду от GitHub
    runs-on: windows-latest

    steps:
      # 1) Чекаутим (выкачиваем) твой код из репо
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Восстанавливаем credentials.json из секрета
      - name: Restore GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json

      # 3) Ставим Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller webdriver-manager gspread oauth2client selenium

      # 5) Собираем exe командой PyInstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile \
            --add-data "chrome-portable;chrome-portable" \
            --add-data "credentials.json;." \
            sync.py

      # 6) Загружаем готовый exe как артефакт
      - name: Upload built EXE
        uses: actions/upload-artifact@v3
        with:
          name: sync-windows
          path: dist/sync.exe
