name: Build Windows EXE

on:
  push:
    branches: [ main ]    # или ваша ветка

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller webdriver-manager gspread oauth2client selenium

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile \
            --add-data "chrome-portable;chrome-portable" \
            --add-data "credentials.json;." \
            --add-data "drivers;drivers" \
            sync.py

      - name: Upload Windows EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: sync-win
          path: dist/sync.exe
