name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller webdriver-manager gspread oauth2client selenium

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile \
            --add-data "chrome-portable;chrome-portable" \
            --add-data "credentials.json;." \
            sync.py

      - name: Debug directory contents
        run: dir dist

      - name: Upload built EXE
        uses: actions/upload-artifact@v3
        with:
          name: sync-windows
          # убедитесь, что dist/sync.exe реально существует:
          path: dist/sync.exe
